export default {
  state: {
    todos: [
      {
        id: 1,
        title: '...',
        content: '123',
        isDone: true,
        isImportant: true,
        isStarred: false,
        isTrashed: false,
        tags: ['前端', '后端', '其它', 'BUG'],
      },
      {
        id: 2,
        title: '...',
        content: '123',
        isDone: true,
        isImportant: true,
        isStarred: false,
        isTrashed: false,
        tags: ['前端', '后端', '其它', 'BUG'],
      },
      {
        id: 3,
        title: '...',
        content: '123',
        isDone: true,
        isImportant: true,
        isStarred: false,
        isTrashed: false,
        tags: ['前端', '后端', '其它', 'BUG'],
      },
      {
        id: 4,
        title: '...',
        content: '123',
        isDone: true,
        isImportant: true,
        isStarred: false,
        isTrashed: false,
        tags: ['前端', '后端', '其它', 'BUG'],
      },
      {
        id: 5,
        title: '...',
        content: '123',
        isDone: true,
        isImportant: true,
        isStarred: false,
        isTrashed: false,
        tags: ['前端', '后端', '其它', 'BUG'],
      },
      {
        id: 6,
        title: '...',
        content: '123',
        isDone: true,
        isImportant: true,
        isStarred: false,
        isTrashed: false,
        tags: ['前端', '后端', '其它', 'BUG'],
      },
      {
        id: 7,
        title: '...',
        content: '123',
        isDone: true,
        isImportant: true,
        isStarred: false,
        isTrashed: false,
        tags: ['前端', '后端', '其它', 'BUG'],
      },
      {
        id: 8,
        title: '...',
        content: '123',
        isDone: true,
        isImportant: true,
        isStarred: false,
        isTrashed: false,
        tags: ['前端', '后端', '其它', 'BUG'],
      },
    ],
  },

  mutations: {
  },

  getters: {
  },
};
